name: Build and deploy to server

# Requires
#   - Server with pm2/nvm
#   -   and repo setup at /srv/eco-projects with ssh-worker user access

on:
  push:
    branches:
      - main

jobs:
  validate-build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: block-pattern-designer
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: validate-build
    steps:
      - name: Deploy by SSH-ing, pulling latest, and cycling the node/next process
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            # Setup nvm
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            # Go to directory and pull
            cd /srv/eco-projects/block-pattern-designer
            git pull

            # Build and Restart
            npm install && npm run build
            pm2 stop pm2.config.json --silent
            pm2 start pm2.config.json --silent && echo "PM2 process started" || echo "PM2 process failed to start"

